server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:3000
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/service/(?<segment>.*), /$\{segment}
            - AddRequestHeader=X-Request-Source, Gateway
        - id: static-resources
          uri: http://localhost:3000  # 프론트엔드 서버 주소
          predicates:
            - Path=/node_modules/**, /src/**, /@*/**
        - id: sales-service
          uri: http://localhost:8090
          predicates:
            - Path=/api/**